BEGIN
INSERT INTO T_CUSTOMER
VALUES(1,,'Fabian','Burzlaff','fabian@gmx.de','test');

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(1,'Tomaten','TestDescription', '1,95', 1);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(2,'Heidelbeeren','TestDescription', '2,95', 2);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(3,'Zwetschgen','TestDescription', '5,95', 2);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(4,'Radieschen','TestDescription', '0,95', 1);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(5,'Dunkle Trauben','TestDescription', '3,95', 1);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(6,'Helle Trauben','TestDescription', '3,95', 1);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(7,'Milch','TestDescription', '1,95', 3);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(8,'Champignos','TestDescription', '1,95', 1);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(9,'Roggenmischbrot','TestDescription', '1,95', 4);

INSERT INTO T_PRODUCT (PROD_ID,PRODUCT_NAME,PRODUCT_DESC,REGULAR_PRICE,CATEGORY)
VALUES(10,'Salami','TestDescription', '2,95', 5);

INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(1, 'Gemüse', 1);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(1, 'Gemüse', 4);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(1, 'Gemüse', 5);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(1, 'Gemüse', 8);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(2, 'Obst', 2);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(2, 'Obst', 3);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(2, 'Obst', 6);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(3, 'Milchprodukte', 7);
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(4, 'Roggenmischbrot', 9); 
INSERT INTO T_PRODUCTCATEGORY (CATEGORY_ID,CATEGORY,PRODUCT_ID)
VALUES(5, 'Fleischprodukte', 10);
END